spring:
  profiles:
    active: ${RUN_ENVIRONMENT:local}

client:
  urls:
    ms-user: ${MS_USER:http://localhost:8081}

redis:
  server:
    urls: redis://${REDIS_CONNECTION_IP:localhost}:${REDIS_CONNECTION_PORT:6379}

token:
  expiration:
    access-token-minutes: ${ACCESS_TOKEN_MINUTES:15}
    refresh-token-minutes: ${REFRESH_TOKEN_MINUTES:21600}
    refresh-token-count: ${REFRESH_TOKEN_COUNT:50}